### ISSUE TITLE
Open Pull Requests July 27th

### ISSUE THREAD

**Issue by sarafiorendi** [MilanoBicocca-pix/cmssw#8]
realistic vertex smearing parameters 2015B 3.8T
76X: https://github.com/cms-sw/cmssw/pull/10384 ==> merged
75X: https://github.com/cms-sw/cmssw/pull/10385 ==> merged
74X: https://github.com/cms-sw/cmssw/pull/10386 ==> merged
71X: https://github.com/cms-sw/cmssw/pull/10387 ==> merged

@rmanzoni

**Comment by rmanzoni** [comment]
all merged
